---
title: "About"
---

# Overview

We all know that R is a critical part of statistics these days, but it can have a steep learning curve and be intimidating to get started with. The [Department of Statistical Sciences](http://www.utstat.utoronto.ca/) (DoSS) toolkit is a free series of open source online modules written by undergraduates, that their fellow students and the public can use to learn the essentials of R. 


# Contributors

- Annie Collins is an undergraduate student in the Department of Mathematics specializing in applied mathematics and statistics with a minor in history and philosophy of science. In her free time, she focusses her efforts on student governance, promoting women's representation in STEM, and working with data in the non-profit and charitable sector.
- Haoluan Chen is an undergraduate student in the Department of Statistical Science specializing in applied statistics. He is interested in applying data science techniques, especially in NLP, to gain insight from the data.
- Isaac Ehrlich is an undergraduate student in Statistics and Cognitive Science at the University of Toronto. He enjoys using R for everything from analysing trends in his recent movie-viewing history, to his past research building models on human categorization.
- Mariam Walaa is an undergraduate student in the Department of Computer and Mathematical Sciences at University of Toronto Scarborough, majoring in Mathematics and minoring in GIS and statistics. Mariam enjoys learning about how to work with data such as spatial and text data to extract insights.
- Marija Pejcinovska is a graduate student in the Department of Statistical Sciences. Her research is motivated by modelling challenges that arise with "complicated" data (sparse/highly biased/poor quality data), usually in the context of social or health inequalities.
- Matthew Wankiewicz is an undergraduate student at the University of Toronto, majoring in Statistics and minoring in Mathematics and the History and Philosophy of Science.
- Michael Chong is a graduate student in the Department of Statistical Sciences. His research aims to build statistical models for demographic estimation in contexts where high quality data are unavailable. There is almost always an active R session on his computer!
- Rohan Alexander is an assistant professor in the Faculty of Information and the Department of Statistical Sciences. Some people convert to catholicism upon marriage, Rohan converted to R. His greatest professional achievement is probably getting a pull request accepted into R for Data Science (it was just fixing a minor typo but still).
- Samantha-Jo Caetano is an assistant professor (teaching stream) in the Department of Statistical Sciences. She loves statistics, socializing, her family, and her dogs, not necessarily in that order.
- Shirley Deng - Shirley is an undergraduate student specializing in Statistics and majoring in Mathematics. Meticulous and soft-hearted, she often finds herself engrossed in new pastimes by the second at the influence of her peers. One of which that has remained a longtime constant - spending an excessive amount of time helping people debug their R code.
- Yena Joo is an undergraduate student majoring in Economics and double minoring in Statistics and Computer Science.


# Pedagogical underpinnings

*Coming soon.*

# Acknowledgements

We gratefully acknowledge the support of Professor Bethany White, Chair Radu Craiu, and the U of T Faculty of Arts & Sciences Pedagogical Innovation and Experimentation Fund.

We'd like to acknowledge the help of:

- Liza Bolton
- Monica Alexander
- Sabrina Sixta

We'd like to thank Alex Cookson for his collection of datasets.

This toolkit builds on, and complements, the work of many others, including:

- Alex Stringer - https://github.com/awstringer1/course-materials 
- Alison Gibbs, Jeff Rosenthal, Nathan Taback - https://stats.onlinelearning.utoronto.ca/
- Bethany White and Jennifer Peter - https://rscidata.utoronto.ca/
- Desirée De Leon and Alison Hill - https://rstudio4edu.github.io/rstudio4edu-book/
- Hasse Walum and Desirée De Leon - https://tinystats.github.io/teacups-giraffes-and-statistics/index.html
- Nathan Taback - https://ntaback.github.io/UofT_STA130/R_resources.html
- Radford Neal - http://www.cs.utoronto.ca/~radford/csc121.S17/

Rohan would like to thank Greg Wilson, for sharing his experience, thoughts, and leadership.


# References

We draw on the open source statistical programming language R and a variety of packages. We are grateful for the work that we build on.

- Barret Schloerke, JJ Allaire, Barbara Borges and Garrick Aden-Buie (2021). learnr: Interactive Tutorials for R. https://rstudio.github.io/learnr/, https://github.com/rstudio/learnr.
- Bodwin, Kelly, and Hunter Glanz (2020). flair: Highlight, Annotate, and Format your R Source Code. R package version 0.0.2. https://CRAN.R-project.org/package=flair
- Chen, Daniel, Barret Schloerke, Garrick Aden-Buie and Garrett Grolemund (2021). gradethis: Automated Feedback for Student Exercises in 'learnr' Tutorials. https://rstudio-education.github.io/gradethis/, https://rstudio.github.io/learnr/, https://github.com/rstudio-education/gradethis.
- de Vries, Andrie, Barret Schloerke and Kenton Russell (2020). sortable: Drag-and-Drop in 'shiny' Apps with 'SortableJS'. R package version 0.4.4. https://CRAN.R-project.org/package=sortable
- Gelfand, Sharla, (2020). opendatatoronto: Access the City of Toronto Open Data Portal. R package version 0.1.4. https://CRAN.R-project.org/package=opendatatoronto
- Hester, Jim, Gábor Csárdi, Hadley Wickham, Winston Chang, Martin Morgan and Dan Tenenbaum (2020). remotes: R Package Installation from Remote Repositories, Including 'GitHub'. R package version 2.2.0. https://CRAN.R-project.org/package=remotes
- R Core Team (2020). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL https://www.R-project.org/.
- Wickham et al., (2019). Welcome to the tidyverse. Journal of Open Source Software, 4(43), 1686, https://doi.org/10.21105/joss.01686



 
# Next steps 

- Assessment
- Modules
	- Iteration
	- Data II
	- Strings
	- Dates
	- Stan
	- Packages
	- Shiny
	- Teaching
- French language version


# Citation

We have a pre-print coming soon.



# How to contribute

The best way to contribute fixes and minor typos is to make a pull request on GitHub. Please make the pull request to the functions folder rather than the specific component that you are using.

If you are interested in contributing lessons or modules, then please contact Rohan Alexander. We are particularly interested in partnering with an institution where the language of instruction is French to develop a French language version.




# Contact

Please contact Rohan (rohan.alexander@utoronto.ca) with any questions, comments, and suggestions.







